### ISSUE TITLE
Allow fetching of appointments for a specific date span

### ISSUE THREAD

**Issue by adewes** [kiebitz-oss/services#16]
As Kiebitz might be used in scenarios where appointments are planned for many months it will become infeasible to keep all appointments on the client at all times. Rather it would be required to only fetch appointments and corresponding bookings for a given date span, e.g. one week. We should modify the `getProviderAppointments` and `getBookings` API endpoints to allow that.

**Comment by tauli** [comment]
@adewes `getBookings` kann ich gerade nicht finden, in welcher Datei ist der definiert? Macht die Funktion vielleicht auch für `getAppointmentsByZipCode` Sinn?
