### ISSUE TITLE
Check validity of provider key when booking appointments

### ISSUE THREAD

**Issue by adewes** [kiebitz-oss/services#23]
Currently users could book appointments for providers whose keys have been revoked. While this is not a security issue as those providers can't access the data anymore it's still a risk as the provider key was probably revoked for a reasons and users shouldn't be able to book appointments with that provider.

We should therefore check that the provider key is still valid before booking an appointment.

In general, only appointments from providers with valid keys will be returned by the `getAppointmentsByZipCode` endpoint, but since that data might be cached it still might happen that appointments from providers without valid keys will be displayed.

**Comment by tauli** [comment]
bookAppointment endpoint will now check if the provider is still in keys::providers before booking the appointment
